import { PrismaClient } from "@prisma/client";

const client = new PrismaClient();

const datasetsToCreate = [
  {
    id: "1",
    name: "jumlah-kelahiran-dan-kematian-bayi-di-kabupaten-garut-2023",
    data: [
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205130,
        kecamatan: "Banjarwangi",
        kelahiran: 1074,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205230,
        kecamatan: "Banyuresmi",
        kelahiran: 1579,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205150,
        kecamatan: "Bayongbong",
        kelahiran: 1809,
        kematian: 8,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205290,
        kecamatan: "Blubur Limbangan",
        kelahiran: 1375,
        kematian: 6,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205030,
        kecamatan: "Bungbulang",
        kelahiran: 1100,
        kematian: 6,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205011,
        kecamatan: "Caringin",
        kelahiran: 671,
        kematian: 1,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205080,
        kecamatan: "Cibalong",
        kelahiran: 728,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205260,
        kecamatan: "Cibatu",
        kelahiran: 1241,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205270,
        kecamatan: "Cibiuk",
        kelahiran: 512,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205151,
        kecamatan: "Cigedug",
        kelahiran: 826,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205111,
        kecamatan: "Cihurip",
        kelahiran: 254,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205120,
        kecamatan: "Cikajang",
        kelahiran: 1170,
        kematian: 6,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205060,
        kecamatan: "Cikelet",
        kelahiran: 695,
        kematian: 12,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205140,
        kecamatan: "Cilawu",
        kelahiran: 1744,
        kematian: 14,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205010,
        kecamatan: "Cisewu",
        kelahiran: 489,
        kematian: 1,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205090,
        kecamatan: "Cisompet",
        kelahiran: 775,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205160,
        kecamatan: "Cisurupan",
        kelahiran: 1818,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205190,
        kecamatan: "Garut Kota",
        kelahiran: 2419,
        kematian: 8,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205280,
        kecamatan: "Kadungora",
        kelahiran: 1307,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205200,
        kecamatan: "Karangpawitan",
        kelahiran: 2429,
        kematian: 11,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205221,
        kecamatan: "Karangtengah",
        kelahiran: 302,
        kematian: 2,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205261,
        kecamatan: "Kersamanah",
        kelahiran: 661,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205240,
        kecamatan: "Leles",
        kelahiran: 1484,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205250,
        kecamatan: "Leuwigoong",
        kelahiran: 843,
        kematian: 7,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205310,
        kecamatan: "Malangbong",
        kelahiran: 2140,
        kematian: 5,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205031,
        kecamatan: "Mekarmukti",
        kelahiran: 314,
        kematian: 0,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205050,
        kecamatan: "Pakenjeng",
        kelahiran: 1287,
        kematian: 13,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205070,
        kecamatan: "Pameungpeuk",
        kelahiran: 783,
        kematian: 5,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205040,
        kecamatan: "Pamulihan",
        kelahiran: 292,
        kematian: 2,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205212,
        kecamatan: "Pangatikan",
        kelahiran: 684,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205171,
        kecamatan: "Pasirwangi",
        kelahiran: 1327,
        kematian: 11,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205100,
        kecamatan: "Peundeuy",
        kelahiran: 359,
        kematian: 1,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205170,
        kecamatan: "Samarang",
        kelahiran: 1361,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205300,
        kecamatan: "Selaawi",
        kelahiran: 636,
        kematian: 5,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205110,
        kecamatan: "Singajaya",
        kelahiran: 803,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205211,
        kecamatan: "Sucinaraja",
        kelahiran: 463,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205161,
        kecamatan: "Sukaresmi",
        kelahiran: 708,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205220,
        kecamatan: "Sukawening",
        kelahiran: 849,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205020,
        kecamatan: "Talegong",
        kelahiran: 451,
        kematian: 1,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205182,
        kecamatan: "Tarogong Kaler",
        kelahiran: 1577,
        kematian: 7,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205181,
        kecamatan: "Tarogong Kidul",
        kelahiran: 2008,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205210,
        kecamatan: "Wanaraja",
        kelahiran: 929,
        kematian: 0,
      },
    ],
  },
  {
    id: "2",
    name: "jumlah-kelahiran-dan-kematian-bayi-di-kabupaten-garut-2022",
    data: [
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205130,
        kecamatan: "Banjarwangi",
        kelahiran: 1171,
        kematian: 8,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205230,
        kecamatan: "Banyuresmi",
        kelahiran: 1533,
        kematian: 13,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205150,
        kecamatan: "Bayongbong",
        kelahiran: 1870,
        kematian: 30,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205290,
        kecamatan: "Blubur Limbangan",
        kelahiran: 1295,
        kematian: 13,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205030,
        kecamatan: "Bungbulang",
        kelahiran: 1251,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205011,
        kecamatan: "Caringin",
        kelahiran: 629,
        kematian: 1,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205080,
        kecamatan: "Cibalong",
        kelahiran: 818,
        kematian: 2,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205260,
        kecamatan: "Cibatu",
        kelahiran: 1251,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205270,
        kecamatan: "Cibiuk",
        kelahiran: 528,
        kematian: 2,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205151,
        kecamatan: "Cigedug",
        kelahiran: 924,
        kematian: 9,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205111,
        kecamatan: "Cihurip",
        kelahiran: 231,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205120,
        kecamatan: "Cikajang",
        kelahiran: 1382,
        kematian: 10,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205060,
        kecamatan: "Cikelet",
        kelahiran: 793,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205140,
        kecamatan: "Cilawu",
        kelahiran: 1652,
        kematian: 8,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205010,
        kecamatan: "Cisewu",
        kelahiran: 389,
        kematian: 0,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205090,
        kecamatan: "Cisompet",
        kelahiran: 678,
        kematian: 5,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205160,
        kecamatan: "Cisurupan",
        kelahiran: 2031,
        kematian: 14,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205190,
        kecamatan: "Garut Kota",
        kelahiran: 2557,
        kematian: 16,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205280,
        kecamatan: "Kadungora",
        kelahiran: 1789,
        kematian: 18,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205200,
        kecamatan: "Karangpawitan",
        kelahiran: 2439,
        kematian: 24,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205221,
        kecamatan: "Karangtengah",
        kelahiran: 317,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205261,
        kecamatan: "Kersamanah",
        kelahiran: 678,
        kematian: 11,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205240,
        kecamatan: "Leles",
        kelahiran: 1518,
        kematian: 12,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205250,
        kecamatan: "Leuwigoong",
        kelahiran: 784,
        kematian: 5,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205310,
        kecamatan: "Malangbong",
        kelahiran: 2201,
        kematian: 10,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205031,
        kecamatan: "Mekarmukti",
        kelahiran: 274,
        kematian: 2,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205050,
        kecamatan: "Pakenjeng",
        kelahiran: 1272,
        kematian: 6,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205070,
        kecamatan: "Pameungpeuk",
        kelahiran: 792,
        kematian: 0,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205040,
        kecamatan: "Pamulihan",
        kelahiran: 298,
        kematian: 1,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205212,
        kecamatan: "Pangatikan",
        kelahiran: 753,
        kematian: 5,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205171,
        kecamatan: "Pasirwangi",
        kelahiran: 1348,
        kematian: 12,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205100,
        kecamatan: "Peundeuy",
        kelahiran: 417,
        kematian: 4,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205170,
        kecamatan: "Samarang",
        kelahiran: 1393,
        kematian: 14,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205300,
        kecamatan: "Selaawi",
        kelahiran: 605,
        kematian: 3,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205110,
        kecamatan: "Singajaya",
        kelahiran: 735,
        kematian: 2,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205211,
        kecamatan: "Sucinaraja",
        kelahiran: 507,
        kematian: 5,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205161,
        kecamatan: "Sukaresmi",
        kelahiran: 765,
        kematian: 9,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205220,
        kecamatan: "Sukawening",
        kelahiran: 936,
        kematian: 16,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205020,
        kecamatan: "Talegong",
        kelahiran: 555,
        kematian: 1,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205182,
        kecamatan: "Tarogong Kaler",
        kelahiran: 1754,
        kematian: 24,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205181,
        kecamatan: "Tarogong Kidul",
        kelahiran: 2724,
        kematian: 7,
      },
      {
        kode_provinsi: 32,
        nama_provinsi: "Jawa Barat",
        kode_kabupaten: 3205,
        nama_kabupaten: "Garut",
        kode_kecamatan: 3205210,
        kecamatan: "Wanaraja",
        kelahiran: 1015,
        kematian: 5,
      },
    ],
  },
];

const seed = async (datasets) => {
  console.log("Seeding data...");

  for (const dataset of datasets) {
    console.log("creating dataset:", dataset.name);
    await client.datasets.upsert({
      where: { id: dataset.id },
      update: dataset,
      create: dataset,
    });
  }
};

seed(datasetsToCreate)
  .then(() => {
    console.log("Data seeded successfully.");
  })
  .catch((error) => {
    console.error("Error seeding data:", error);
  })
  .finally(() => {
    client.$disconnect();
    console.log("Disconnected from database.");
  });
